

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///


/// Example:


/// ```dart

/// import 'firebase_options.dart';

/// // ...
/// await Firebase.initializeApp(

///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiTV6wWgT1PaaQnNITOqo2o_PlipqCDh4',
    appId: '1:1091526125564:web:4a6d9bb8a78f4bb9433479',
    messagingSenderId: '1091526125564',
    projectId: 'crudfunc-794d7',
    authDomain: 'crudfunc-794d7.firebaseapp.com',
    storageBucket: 'crudfunc-794d7.firebasestorage.app',
    measurementId: 'G-8D1MQJ1N8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRaVNRx1Fp5nLANmQnpBamOUb4G1JKUd8',
    appId: '1:1091526125564:android:b9bdef39b11d97ab433479',
    messagingSenderId: '1091526125564',
    projectId: 'crudfunc-794d7',
    storageBucket: 'crudfunc-794d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr8VZyDnw-jSKboqhxrpnbXuIItaWq8CQ',
    appId: '1:1091526125564:ios:d58b7a48f62a6f5a433479',
    messagingSenderId: '1091526125564',
    projectId: 'crudfunc-794d7',
    storageBucket: 'crudfunc-794d7.firebasestorage.app',
    iosBundleId: 'com.example.signSpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr8VZyDnw-jSKboqhxrpnbXuIItaWq8CQ',
    appId: '1:1091526125564:ios:d58b7a48f62a6f5a433479',
    messagingSenderId: '1091526125564',
    projectId: 'crudfunc-794d7',
    storageBucket: 'crudfunc-794d7.firebasestorage.app',
    iosBundleId: 'com.example.signSpark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7OZa5I6xeocug7p484laIFTYgwS_JeMw',
    appId: '1:1091526125564:web:ef66443b942885a3433479',
    messagingSenderId: '1091526125564',
    projectId: 'crudfunc-794d7',
    authDomain: 'crudfunc-794d7.firebaseapp.com',
    storageBucket: 'crudfunc-794d7.firebasestorage.app',
    measurementId: 'G-5EJ69QKKGJ',
  );
}
